params = [
    {
        "name": "Sample Rate",
        "type": "float",
        "value": 200000.0,
        "suffix": "Hz",
        "siPrefix": True,
        # "default": False,
        # "expanded": False,
    },
    {
        "name": "Sample format",
        "type": "float",
        "value": 1,
        "suffix": "",
        "siPrefix": True,
    },
    {
        "name": "DMA buffer size",
        "type": "float",
        "value": 50,
        "suffix": "ms",
        "siPrefix": True,
    },
    {
        "name": "Num DMA buffers",
        "type": "int",
        "value": 2,
        "suffix": "",
        "siPrefix": True,
    },
    {
        "name": "Drop first samples",
        "type": "int",
        "value": 2,
        "suffix": "mc",
        "siPrefix": True,
    },
    {
        "name": "DAC sample rate",
        "type": "float",
        "value": 200000.0,
        "suffix": "Hz",
        "siPrefix": True,
    },
    {
        "name": "Duration",
        "type": "float",
        "value": 0.001,
        "suffix": "S",
        "siPrefix": True,
    },
    {
        "name": "Chirp start frequency",
        "type": "float",
        "value": 7000.0,
        "suffix": "Hz",
        "siPrefix": True,
    },
    {
        "name": "Chirp stop frequency",
        "type": "float",
        "value": 17000.0,
        "suffix": "Hz",
        "siPrefix": True,
    },
    {
        "name": "Amplitude",
        "type": "float",
        "value": 1.0,
        "suffix": "V",
        "siPrefix": True,
    },
    {
        "name": "Phase",
        "type": "float",
        "limits": [0, 360],
        "value": 0.0,
        "suffix": "degrees",
        "siPrefix": True,
    },
    {
        "name": "Signal type",
        "type": "list",
        "type": "list",
        "limits": ["linear", "quad", "log", "sin", "triangle"],
        "value": "linear",
    },
    {"name": "Auto restart", "type": "bool", "value": True},
    {"name": "Run back", "type": "bool", "value": False},
    {"name": "Start", "type": "bool", "value": False, "visible":False},
]